<!DOCTYPE HTML>
<html manifest="">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10, user-scalable=yes">

	<title>404 Not Found</title>

	<style>
		body {
			font-family: Arial, Tahoma, Verdana, sans-serif;
		}
	</style>
</head>
<body>
<table width="100%" style="height: 100%">
	<tr>
		<td align="center" valign="middle">
			<h2>404 Not Found</h2>
			URI <strong><?= $uri ?></strong> was not found on this server.
		</td>
	</tr>
</table>
</body>
</html>
