<?php
namespace Tests\Models;

use Models\Banners;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-18 at 21:29:23.
 */
class BannersTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Banners
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Banners;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Models\Banners::__construct
	 */
	public function testConstruct()
	{
		$expected = realpath(__DIR__ . '/../../../data');
		$msg = 'Banners::__construct() wrong behavior!';
		$this->assertAttributeSame($expected, 'dir', $this->object, $msg);

		$expected = realpath(__DIR__ . '/../../../data') . '/banners.csv';
		$this->assertAttributeSame($expected, 'path', $this->object, $msg);
	}

	/**
	 * @covers       Models\Banners::read
	 *
	 * @dataProvider readProvider
	 *
	 * @param $expected
	 * @param $start
	 * @param $offset
	 */
	public function testRead($expected, $start, $offset)
	{
		$this->object->setStart($start);
		$this->object->setOffset($offset);

		$actual = $this->object->read();
		$msg = 'Banners::read() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	public function readProvider()
	{
		return [
			[
				[
					0 => [
						0 => 4404474,
						1 => 13653389,
						2 => '',
						3 => 1907369,
						4 => 2810,
						5 => 22688.0,
					],
					1 => [
						0 => 2707999,
						1 => 10629533,
						2 => 'Title1',
						3 => 2757430,
						4 => 1746,
						5 => 19850.639999999999,
					],
					2 => [
						0 => 3978008,
						1 => 12963762,
						2 => '',
						3 => 1839146,
						4 => 2096,
						5 => 19049.91,
					],
					3 => [
						0 => 3918762,
						1 => 12883281,
						2 => 'Title1',
						3 => 3421253,
						4 => 1345,
						5 => 16915.990000000002,
					],
					4 => [
						0 => 2707613,
						1 => 10627329,
						2 => 'Кредит под 12%',
						3 => 4649362,
						4 => 1337,
						5 => 15990.219999999999,
					],
				],
				0, 5
			],
			[
				[
					0 => [
						0 => 3978008,
						1 => 12963762,
						2 => '',
						3 => 1839146,
						4 => 2096,
						5 => 19049.91,
					],
					1 => [
						0 => 3918762,
						1 => 12883281,
						2 => 'Title1',
						3 => 3421253,
						4 => 1345,
						5 => 16915.990000000002,
					]

				],
				2, 2
			]
		];
	}

	/**
	 * @covers Models\Banners::setStart
	 *
	 * @param $data
	 * @param $expected
	 *
	 * @dataProvider startProvider
	 */
	public function testSetStart($data, $expected)
	{
		$actual = $this->object->setStart($data);
		$msg = 'Banners::setStart() return wrong result!';
		$this->assertSame($this->object, $actual, $msg);

		$msg = 'Banners::setStart() wrong behavior!';
		$this->assertAttributeSame($expected, 'start', $this->object, $msg);
	}

	public function startProvider()
	{
		return [
			[100, 100],
			[null, 0],
			[10, 10]
		];
	}

	/**
	 * @covers       Models\Banners::setOffset
	 *
	 * @dataProvider offsetProvider
	 *
	 * @param $data
	 * @param $expected
	 */
	public function testSetOffset($data, $expected)
	{
		$actual = $this->object->setOffset($data);
		$msg = 'Banners::setOffset() return wrong result!';
		$this->assertSame($this->object, $actual, $msg);

		$msg = 'Banners::setOffset() wrong behavior!';
		$this->assertAttributeSame($expected, 'offset', $this->object, $msg);
	}

	public function offsetProvider()
	{
		return [
			[100, 100],
			[null, 25],
			[10, 10]
		];
	}

	/**
	 * @covers       Models\Banners::fixTypes
	 *
	 * @dataProvider fixTypesProvider
	 *
	 * @param $key
	 * @param $value
	 * @param $expected
	 */
	public function testFixTypes($key, $value, $expected)
	{
		$actual = $this->object->fixTypes($key, $value);

		$msg = 'Banners::fixTypes() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	public function fixTypesProvider()
	{
		return [
			[0, '123', 123],
			[1, '234', 234],
			[2, 234, '234'],
			[3, '1234', 1234],
			[4, '300', 300],
			[5, '23,23', 23.23]
		];
	}


	/**
	 * @covers       Models\Banners::fixTypes
	 *
	 * @dataProvider fixTypesExceptionProvider
	 *
	 * @expectedException \Exceptions\RuntimeException
	 *
	 * @param $key
	 * @param $value
	 */
	public function testFixTypeException($key, $value)
	{
		$this->object->fixTypes($key, $value);
	}

	public function fixTypesExceptionProvider()
	{
		return [
			[7, '234'],
			[500, '2345']
		];
	}

	/**
	 * @covers Models\Banners::getTotalLines
	 */
	public function testGetTotalLines()
	{
		$expected = 9100;

		$actual = $this->object->getTotalLines();
		$msg = 'Banners::getTotalLines() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}
}
