<?php
namespace Tests\Models;

use Models\Campaigns;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-18 at 22:18:42.
 */
class CampaignsTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Campaigns
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Campaigns;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers       Models\Campaigns::read
	 */
	public function testRead()
	{
		//TODO Implement test
	}
}
