<?php
namespace Tests\Models;

use Models\Campaigns;

require 'fopen_stub.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-18 at 22:18:42.
 */
class CampaignsTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Campaigns
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Campaigns;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers       Models\Campaigns::read
	 *
	 * @param $expected
	 * @dataProvider readProvider
	 *
	 * @throws \Exceptions\RuntimeException
	 */
	public function testRead($expected)
	{
		$actual = $this->object->read();
		$msg = 'Campaigns::read() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	public function readProvider()
	{
		return [
			[
				[
					0 => [
						0 => 4404474,
						1 => 'Пенс_КлючиКредит_Рег_240х_МЖ_55+',
						2 => 'FM',
						3 => 55,
						4 => 75,
						5 => 0,
						6 => 'CPC',
					],
					1 => [
						0 => 2707999,
						1 => 'Пенс_РМ30дн_Рег_90х_МЖ_55+',
						2 => 'FM',
						3 => 55,
						4 => 75,
						5 => 0,
						6 => 'CPC',
					],
					2 => [
						0 => 3978008,
						1 => 'Ден_КлючиКредит_Рег_240х_МЖ_45-54',
						2 => 'FM',
						3 => 45,
						4 => 54,
						5 => 500,
						6 => 'CPC',
					],
					3 => [
						0 => 3918762,
						1 => 'Пенс_КлючиКредит_Рег_F_55+',
						2 => 'F',
						3 => 55,
						4 => 75,
						5 => 0,
						6 => 'CPC',
					],
					4 => [
						0 => 2707613,
						1 => 'Ден_РМ30дн_Рег_90х_Ж_35-44',
						2 => 'F',
						3 => 35,
						4 => 44,
						5 => 0,
						6 => 'CPC',
					],
				]
			]
		];
	}
}
