<?php
namespace Tests\Controllers;

use Controllers\Home;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-18 at 20:00:42.
 */
class HomeTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Home
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Home;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Controllers\Home::get
	 */
	public function testGet()
	{
		$expected = [];
		$actual = $this->object->get();

		$msg = 'Home::get() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}
}
