<?php
namespace Tests\Exceptions;

use Exceptions\HttpResponseException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-18 at 20:33:33.
 */
class HttpResponseExceptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers       Exceptions\HttpResponseException::__construct
	 */
	public function testConstruct()
	{
		$expected = '0';

		ini_set('display_errors', 1);
		ini_set('log_errors', 1);

		new HttpResponseException;

		$actual = ini_get('display_errors');
		$msg = 'HttpResponseException::__construct() does\'t set display_errors ini-param';
		$this->assertSame($expected, $actual, $msg);

		$actual = ini_get('log_errors');
		$msg = 'HttpResponseException::__construct() does\'t set log_errors ini-param';
		$this->assertSame($expected, $actual, $msg);
	}
}
